"use client";

import "../styles/globals.css";
import Providers from "@/app/providers";
import { DM_Sans } from "@next/font/google";
import QueryProvider from "../utils/queryProvider";
import React from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const dmSans = DM_Sans({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body className={`${dmSans.className}`}>
        <Providers>
          <QueryProvider>{children}</QueryProvider>
        </Providers>
        <ToastContainer />
      </body>
    </html>
  );
}
